name: metaDungeon
version: '1.0'
main: sbs.immovablerod.metaDungeon.MetaDungeon
api-version: '1.13'
depend: [NBTAPI]
load: STARTUP
commands:
  init_map:
    description: testing
    usage: /init_map <name> <x> <y> <z> <xdelta> <ydelta> <zdelta>
    permission: metaDungeon.init_map
    permission-message: You don't have <permission>
  start_game:
    description: testing
    usage: /start_game <name>
    permission: metaDungeon.start_game
    permission-message: You don't have <permission>
  stop_game:
    description: testing
    usage: /stop_game <name>
    permission: metaDungeon.stop_game
    permission-message: You don't have <permission>
  md_apply_effect:
    description: testing
    usage: /md_apply_effect <duration> <level>
    permission: metaDungeon.md_apply_effect
    permission-message: You don't have <permission>
