name: MetaDungeon
version: '1.2'
main: sbs.immovablerod.metaDungeon.MetaDungeon
author: SkillfulHacks
api-version: '1.21.10'
depend: [NBTAPI]
load: STARTUP
commands:
  start_game:
    description: testing
    usage: /start_game <name>
    permission: metaDungeon.start_game
    permission-message: You don't have <permission>
  stop_game:
    description: testing
    usage: /stop_game <name>
    permission: metaDungeon.stop_game
    permission-message: You don't have <permission>
  md_apply_effect:
    description: testing
    usage: /md_apply_effect <name> <duration> <level>
    permission: metaDungeon.md_apply_effect
    permission-message: You don't have <permission>
  md_event:
    description: testing
    usage: /md_event <name> <level>
    permission: metaDungeon.md_event
    permission-message: You don't have <permission>
  md_give:
    description: testing
    usage: /md_give <name>
    permission: metaDungeon.md_give
    permission-message: You don't have <permission>